Repository prgrms-web-devcourse/Team_Ahpuh_Surf_BE, pull requests merged in 2021-12, with the labels that each got.

#7 gitignore 수정
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/saveactions_settings.xml
  .idea/vcs.xml
Labels: hot fix

#8 Feature/#5 Category CUD구현
  build.gradle
  src/main/java/org/ahpuh/backend/category/converter/CategoryConverter.java
  src/main/java/org/ahpuh/backend/category/dto/CategoryCreateRequestDto.java
  src/main/java/org/ahpuh/backend/category/dto/CategoryResponseDto.java
  src/main/java/org/ahpuh/backend/category/dto/CategoryUpdateRequestDto.java
  src/main/java/org/ahpuh/backend/category/entity/Category.java
  src/main/java/org/ahpuh/backend/category/repository/CategoryRepository.java
  src/main/java/org/ahpuh/backend/category/service/CategoryService.java
  src/main/java/org/ahpuh/backend/category/service/CategoryServiceImpl.java
  src/main/java/org/ahpuh/backend/common/entity/BaseEntity.java
  src/main/java/org/ahpuh/backend/common/exception/EntityExceptionSuppliers.java
  src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
Labels: feat

#11 JWT 구현
  build.gradle
  src/main/java/org/ahpuh/backend/config/JwtConfig.java
  src/main/java/org/ahpuh/backend/config/WebSecurityConfig.java
  src/main/java/org/ahpuh/backend/jwt/Jwt.java
  src/main/java/org/ahpuh/backend/jwt/JwtAuthentication.java
  src/main/java/org/ahpuh/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/org/ahpuh/backend/jwt/JwtAuthenticationProvider.java
  src/main/java/org/ahpuh/backend/jwt/JwtAuthenticationToken.java
Labels: feat

#13 USER 로그인, 회원가입 구현
  build.gradle
  src/main/java/org/ahpuh/backend/user/controller/UserController.java
  src/main/java/org/ahpuh/backend/user/converter/UserConverter.java
  src/main/java/org/ahpuh/backend/user/dto/UserJoinRequestDto.java
  src/main/java/org/ahpuh/backend/user/dto/UserLoginDto.java
  src/main/java/org/ahpuh/backend/user/dto/UserLoginRequestDto.java
  src/main/java/org/ahpuh/backend/user/dto/UserLoginResponseDto.java
  src/main/java/org/ahpuh/backend/user/dto/UserResponseDto.java
  src/main/java/org/ahpuh/backend/user/dto/UserUpdateRequestDto.java
  src/main/java/org/ahpuh/backend/user/entity/User.java
  src/main/java/org/ahpuh/backend/user/repository/UserRepository.java
  src/main/java/org/ahpuh/backend/user/service/UserService.java
  src/main/java/org/ahpuh/backend/user/service/UserServiceImpl.java
  src/test/java/org/ahpuh/backend/user/controller/UserControllerTest.java
Labels: feat

#14 Post CRUD 구현
  .github/workflows/gradle.yml
  .gitignore
  src/main/java/org/ahpuh/backend/category/entity/Category.java
  src/main/java/org/ahpuh/backend/category/repository/CategoryRepository.java
  src/main/java/org/ahpuh/backend/common/entity/BaseEntity.java
  src/main/java/org/ahpuh/backend/common/exception/NotFoundException.java
  src/main/java/org/ahpuh/backend/common/response/ApiResponse.java
  src/main/java/org/ahpuh/backend/post/controller/PostController.java
  src/main/java/org/ahpuh/backend/post/converter/PostConverter.java
  src/main/java/org/ahpuh/backend/post/dto/PostDto.java
  src/main/java/org/ahpuh/backend/post/dto/PostIdResponse.java
  src/main/java/org/ahpuh/backend/post/dto/PostRequest.java
  src/main/java/org/ahpuh/backend/post/entity/Post.java
  src/main/java/org/ahpuh/backend/post/repository/PostRepository.java
  src/main/java/org/ahpuh/backend/post/service/PostService.java
  src/main/java/org/ahpuh/backend/post/service/PostServiceImpl.java
  src/main/java/org/ahpuh/backend/user/entity/User.java
  src/test/java/org/ahpuh/backend/post/controller/PostControllerTest.java
  src/test/java/org/ahpuh/backend/post/service/PostServiceImplTest.java
Labels: feat

#23 Entity Exception Handler
  build.gradle
  src/main/java/org/ahpuh/surf/category/service/CategoryServiceImpl.java
  src/main/java/org/ahpuh/surf/common/exception/EntityExceptionHandler.java
  src/main/java/org/ahpuh/surf/common/exception/EntityExceptionSuppliers.java
  src/main/java/org/ahpuh/surf/common/exception/NotFoundException.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/post/service/PostServiceImplTest.java
Labels: refactor

#24 USER API 추가 구현
  .gitignore
  src/main/java/org/ahpuh/surf/category/entity/Category.java
  src/main/java/org/ahpuh/surf/common/exception/EntityExceptionHandler.java
  src/main/java/org/ahpuh/surf/config/WebSecurityConfig.java
  src/main/java/org/ahpuh/surf/jwt/Claims.java
  src/main/java/org/ahpuh/surf/jwt/Jwt.java
  src/main/java/org/ahpuh/surf/jwt/JwtAuthenticationFilter.java
  src/main/java/org/ahpuh/surf/jwt/JwtAuthenticationProvider.java
  src/main/java/org/ahpuh/surf/user/controller/UserController.java
  src/main/java/org/ahpuh/surf/user/converter/UserConverter.java
  src/main/java/org/ahpuh/surf/user/dto/UserDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserJoinRequestDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserJoinResponseDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserLoginDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserLoginRequestDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserUpdateRequestDto.java
  src/main/java/org/ahpuh/surf/user/entity/User.java
  src/main/java/org/ahpuh/surf/user/service/UserService.java
  src/main/java/org/ahpuh/surf/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/test/java/org/ahpuh/surf/category/service/CategoryServiceTest.java
  src/test/java/org/ahpuh/surf/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: feat, fix, test, style

#25 Feature/#10 CATEGORY 조회 기능들 구현
  src/main/java/org/ahpuh/surf/category/controller/CategoryController.java
  src/main/java/org/ahpuh/surf/category/converter/CategoryConverter.java
  src/main/java/org/ahpuh/surf/category/dto/CategoryDetailResponseDto.java
  src/main/java/org/ahpuh/surf/category/dto/CategoryResponseDto.java
  src/main/java/org/ahpuh/surf/category/dto/CategoryUpdateRequestDto.java
  src/main/java/org/ahpuh/surf/category/entity/Category.java
  src/main/java/org/ahpuh/surf/category/service/CategoryServiceImpl.java
  src/test/java/org/ahpuh/surf/category/service/CategoryServiceTest.java
Labels: feat, fix, test

#29 User 수정, 삭제 API 수정
  src/main/java/org/ahpuh/surf/user/controller/UserController.java
  src/main/java/org/ahpuh/surf/user/entity/User.java
  src/main/resources/sql/schema.sql
  src/test/java/org/ahpuh/surf/user/controller/UserControllerTest.java
Labels: feat, test

#30 FOLLOW 도메인 API 구현
  src/main/java/org/ahpuh/surf/common/exception/EntityExceptionHandler.java
  src/main/java/org/ahpuh/surf/follow/controller/FollowController.java
  src/main/java/org/ahpuh/surf/follow/converter/FollowConverter.java
  src/main/java/org/ahpuh/surf/follow/dto/FollowUserDto.java
  src/main/java/org/ahpuh/surf/follow/entity/Follow.java
  src/main/java/org/ahpuh/surf/follow/repository/FollowRepository.java
  src/main/java/org/ahpuh/surf/follow/service/FollowService.java
  src/main/java/org/ahpuh/surf/follow/service/FollowServiceImpl.java
  src/main/java/org/ahpuh/surf/jwt/JwtAuthenticationProvider.java
  src/main/java/org/ahpuh/surf/user/converter/UserConverter.java
  src/main/java/org/ahpuh/surf/user/entity/Permission.java
  src/main/java/org/ahpuh/surf/user/entity/User.java
  src/main/resources/sql/schema.sql
  src/test/java/org/ahpuh/surf/follow/controller/FollowControllerTest.java
  src/test/java/org/ahpuh/surf/user/controller/UserControllerTest.java
Labels: feat, fix, test, docs

#35 Feature/#26 무한 스크롤 구현
  src/main/java/org/ahpuh/surf/category/controller/CategoryController.java
  src/main/java/org/ahpuh/surf/category/dto/CategoryCreateRequestDto.java
  src/main/java/org/ahpuh/surf/category/service/CategoryService.java
  src/main/java/org/ahpuh/surf/category/service/CategoryServiceImpl.java
  src/main/java/org/ahpuh/surf/common/response/CursorResult.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/PostResponseDto.java
  src/main/java/org/ahpuh/surf/post/entity/Post.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/category/controller/CategoryControllerTest.java
  src/test/java/org/ahpuh/surf/category/service/CategoryServiceTest.java
  src/test/java/org/ahpuh/surf/post/service/PostServiceImplTest.java
Labels: feat

#36 둘러보기 API (QueryDsl), 좋아요 도메인, S3 파일 업로드 구현
  build.gradle
  src/main/java/org/ahpuh/surf/common/s3/S3Service.java
  src/main/java/org/ahpuh/surf/config/ReadOnlyMultipartFormDataEndpointConverter.java
  src/main/java/org/ahpuh/surf/config/WebMvcConfig.java
  src/main/java/org/ahpuh/surf/config/WebSecurityConfig.java
  src/main/java/org/ahpuh/surf/follow/controller/FollowController.java
  src/main/java/org/ahpuh/surf/follow/converter/FollowConverter.java
  src/main/java/org/ahpuh/surf/follow/entity/Follow.java
  src/main/java/org/ahpuh/surf/follow/service/FollowService.java
  src/main/java/org/ahpuh/surf/follow/service/FollowServiceImpl.java
  src/main/java/org/ahpuh/surf/like/controller/LikeController.java
  src/main/java/org/ahpuh/surf/like/converter/LikeConverter.java
  src/main/java/org/ahpuh/surf/like/entity/Like.java
  src/main/java/org/ahpuh/surf/like/repository/LikeRepository.java
  src/main/java/org/ahpuh/surf/like/service/LikeService.java
  src/main/java/org/ahpuh/surf/like/service/LikeServiceImpl.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/dto/FollowingPostDto.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryQuerydsl.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/main/java/org/ahpuh/surf/user/controller/UserController.java
  src/main/java/org/ahpuh/surf/user/converter/UserConverter.java
  src/main/java/org/ahpuh/surf/user/dto/UserDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserJoinRequestDto.java
  src/main/java/org/ahpuh/surf/user/dto/UserUpdateRequestDto.java
  src/main/java/org/ahpuh/surf/user/entity/User.java
  src/main/java/org/ahpuh/surf/user/repository/UserRepository.java
  src/main/java/org/ahpuh/surf/user/service/UserService.java
  src/main/java/org/ahpuh/surf/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/sql/schema.sql
  src/test/java/org/ahpuh/surf/category/controller/CategoryControllerTest.java
  src/test/java/org/ahpuh/surf/category/service/CategoryServiceTest.java
  src/test/java/org/ahpuh/surf/common/s3/S3ServiceTest.java
  src/test/java/org/ahpuh/surf/follow/controller/FollowControllerTest.java
  src/test/java/org/ahpuh/surf/like/controller/LikeControllerTest.java
  src/test/java/org/ahpuh/surf/like/repository/LikeRepositoryTest.java
  src/test/java/org/ahpuh/surf/post/repository/PostRepositoryTest.java
  src/test/java/org/ahpuh/surf/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: feat, fix, test, style, docs

#37 Post 1년치 점수, 개수 조회 기능, 즐겨찾기 구현
  src/main/java/org/ahpuh/surf/aop/SoftDelete.java
  src/main/java/org/ahpuh/surf/category/dto/CategorySimpleDto.java
  src/main/java/org/ahpuh/surf/common/exception/EntityExceptionHandler.java
  src/main/java/org/ahpuh/surf/common/response/ApiResponse.java
  src/main/java/org/ahpuh/surf/config/QuerydslConfig.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/PostCountDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostIdResponseDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostRequestDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostScoreDto.java
  src/main/java/org/ahpuh/surf/post/entity/Post.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryQuerydsl.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/like/controller/LikeControllerTest.java
  src/test/java/org/ahpuh/surf/like/repository/LikeRepositoryTest.java
  src/test/java/org/ahpuh/surf/post/controller/PostControllerTest.java
  src/test/java/org/ahpuh/surf/post/repository/PostRepositoryTest.java
  src/test/java/org/ahpuh/surf/post/service/PostServiceImplTest.java
Labels: feat

#42 Post 일년치 게시글 점수 조회 구현
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/PostScoreCategoryDto.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryQuerydsl.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/post/PostTest.java
Labels: feat, test

#45 API 테스트 및 수정
  src/main/java/org/ahpuh/surf/category/converter/CategoryConverter.java
  src/main/java/org/ahpuh/surf/category/dto/CategoryResponseDto.java
  src/main/java/org/ahpuh/surf/category/entity/Category.java
  src/main/java/org/ahpuh/surf/category/repository/CategoryRepository.java
  src/main/java/org/ahpuh/surf/category/service/CategoryService.java
  src/main/java/org/ahpuh/surf/category/service/CategoryServiceImpl.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/entity/Post.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/category/service/CategoryServiceTest.java
Labels: fix, refactor

#50 한달 게시글 조회 오류 수정
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
Labels: hot fix

#49 Post 1년치 게시글 점수 조회 API 응답 수정
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/PostScoreDto.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/post/PostTest.java
  src/test/java/org/ahpuh/surf/post/service/PostServiceImplTest.java
Labels: fix

#47 게시글 등록, 수정 시 파일을 업로드할 수 있도록 S3 연동
  src/main/java/org/ahpuh/surf/common/s3/S3Service.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/PostDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostRequestDto.java
  src/main/java/org/ahpuh/surf/post/entity/Post.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/main/java/org/ahpuh/surf/user/controller/UserController.java
  src/test/java/org/ahpuh/surf/common/s3/S3ServiceTest.java
  src/test/java/org/ahpuh/surf/post/controller/PostControllerTest.java
  src/test/java/org/ahpuh/surf/post/service/PostServiceImplTest.java
Labels: feat, test, style

#52 둘러보기 커서 페이징 적용, 좋아요 도메인 리팩토링
  src/main/java/org/ahpuh/surf/like/controller/LikeController.java
  src/main/java/org/ahpuh/surf/like/converter/LikeConverter.java
  src/main/java/org/ahpuh/surf/like/entity/Like.java
  src/main/java/org/ahpuh/surf/like/repository/LikeRepository.java
  src/main/java/org/ahpuh/surf/like/service/LikeServiceImpl.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/AllPostResponseDto.java
  src/main/java/org/ahpuh/surf/post/dto/FollowingPostDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostDto.java
  src/main/java/org/ahpuh/surf/post/dto/PostIdResponseDto.java
  src/main/java/org/ahpuh/surf/post/entity/Post.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryQuerydsl.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/like/controller/LikeControllerTest.java
  src/test/java/org/ahpuh/surf/like/repository/LikeRepositoryTest.java
  src/test/java/org/ahpuh/surf/post/repository/PostRepositoryTest.java
  src/test/java/org/ahpuh/surf/post/service/PostServiceImplTest.java
Labels: feat, fix, test, style

#54 수정보완
  src/main/java/org/ahpuh/surf/category/service/CategoryServiceImpl.java
  src/main/java/org/ahpuh/surf/common/s3/S3Service.java
  src/main/java/org/ahpuh/surf/common/s3/S3ServiceImpl.java
  src/main/java/org/ahpuh/surf/follow/repository/FollowRepository.java
  src/main/java/org/ahpuh/surf/follow/service/FollowServiceImpl.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/entity/Post.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/main/java/org/ahpuh/surf/user/converter/UserConverter.java
  src/main/java/org/ahpuh/surf/user/dto/UserDto.java
  src/main/java/org/ahpuh/surf/user/service/UserServiceImpl.java
  src/test/java/org/ahpuh/surf/config/MockAwsS3Service.java
  src/test/java/org/ahpuh/surf/like/controller/LikeControllerTest.java
  src/test/java/org/ahpuh/surf/user/controller/UserControllerTest.java
Labels: feat, fix, refactor, test, style, hot fix

#56 통합테스트 진행하며 발생한 버그 수정
  src/main/java/org/ahpuh/surf/like/controller/LikeController.java
  src/main/java/org/ahpuh/surf/like/service/LikeService.java
  src/main/java/org/ahpuh/surf/like/service/LikeServiceImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryQuerydsl.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/post/repository/PostRepositoryTest.java
Labels: feat, fix

#58 Fix/#57 기타 수정
  src/main/java/org/ahpuh/surf/post/dto/FollowingPostDto.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/post/repository/PostRepositoryTest.java
Labels: fix

#60 최신 게시글 100개 조회
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/ExploreDto.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryQuerydsl.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/test/java/org/ahpuh/surf/post/repository/PostRepositoryTest.java
Labels: feat

#61 리팩토링
  src/main/java/org/ahpuh/surf/like/converter/LikeConverter.java
  src/main/java/org/ahpuh/surf/like/entity/Like.java
  src/main/java/org/ahpuh/surf/like/repository/LikeRepository.java
  src/main/java/org/ahpuh/surf/like/service/LikeServiceImpl.java
  src/main/java/org/ahpuh/surf/post/controller/PostController.java
  src/main/java/org/ahpuh/surf/post/converter/PostConverter.java
  src/main/java/org/ahpuh/surf/post/dto/RecentPostDto.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepository.java
  src/main/java/org/ahpuh/surf/post/repository/PostRepositoryImpl.java
  src/main/java/org/ahpuh/surf/post/service/PostService.java
  src/main/java/org/ahpuh/surf/post/service/PostServiceImpl.java
  src/main/java/org/ahpuh/surf/user/entity/User.java
  src/test/java/org/ahpuh/surf/like/controller/LikeControllerTest.java
Labels: fix, refactor
